---
version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    volumes:
      - /opt/docker/data:/usr/share/nginx/html:ro
    ports:
      - 80:${NGINX_PORT}/tcp
