---
galaxy_info:
  author: Patrick Becker <galaxy@thinkbox.center>
  description: Install Docker from the official repository.
  license: MIT

  min_ansible_version: "2.13"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - jammy
        - focal

dependencies: []
