---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # - name: ubuntu-23.04
  #   image: ubuntu:23.04
  # - name: ubuntu-22.04
  #   image: ubuntu:22.04
  - name: ubuntu-20.04
    image: ubuntu:20.04
  # - name: debian-12
  #   image: debian:12
  - name: debian-11
    image: debian:11
provisioner:
  name: ansible
  config_options:
    tags:
      skip: service
  inventory:
    group_vars:
      all:
        ansible_user: root
scenario:
  name: default
