---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # This step checks the following things:
    #
    # - Was the docker-compose templates copied?
    # - Was the .env file copied? (Defines NGINX_PORT=80)
    # - Was the .env file found by docker-compose and the variables inserted?
    #
    - name: Get Docker compose fingerprint
      ansible.builtin.command: docker compose config --hash=nginx
        chdir=/opt/docker
      changed_when: false
      register: docker_compose_hash

    - name: Output information about the Docker fingerprint step
      ansible.builtin.debug:
        msg: "{{ docker_compose_hash }}"

    - name: Validate Docker compose output
      ansible.builtin.assert:
        that:
          - docker_compose_hash is defined
          - docker_compose_hash.stdout == "nginx c6c17a5aec732e20a5801f975edce845069526c172df5ffba6cf9a773101011a"
        fail_msg: "Required Docker compose files are missing or incomplete."
        success_msg: "Required Docker compose files were successfully verified."

    - name: Ensure templates have been copied
      block:
        - name: Get file stats
          ansible.builtin.stat:
            path: "/opt/docker/data/shared.html"
          register: file_info

        - name: Verify file stats
          ansible.builtin.assert:
            that:
              - file_info is defined
              - file_info.stat is defined
              - file_info.stat.exists == true
              - file_info.stat.isdir == false
            fail_msg: "File 'shared.html' was not found."
            success_msg: "File 'shared.html' has passed."
