---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # This step checks the following things:
    #
    # - Was the docker-compose templates copied?
    # - Was the .env file copied? (Defines NGINX_PORT=80)
    # - Was the .env file found by docker-compose and the variables inserted?
    #
    - name: Get Docker compose fingerprint
      ansible.builtin.command: docker compose config --hash=nginx
        chdir=/opt/docker
      changed_when: false
      register: docker_compose_hash

    - name: Output information about the Docker fingerprint step
      ansible.builtin.debug:
        msg: "{{ docker_compose_hash }}"

    - name: Validate Docker compose output
      ansible.builtin.assert:
        that:
          - docker_compose_hash is defined
          - docker_compose_hash.stdout == "nginx 7b99edc1470b82c23cbd630f2c4714c8837519f788c752f4fcca92d975a30390"
        fail_msg: "Required Docker compose files are missing or incomplete."
        success_msg: "Required Docker compose files were successfully verified."
