---
- name: Stop containers
  when: not ansible_check_mode and 'service' not in ansible_skip_tags
  become: true
  community.docker.docker_compose:
    project_src: "{{ docker_compose_destination }}"
    state: absent
